export default actionType = {
    CREATE_TICKET: "CREATE_TICKET",
    CREATE_TICKET_SUCCESS: "CREATE_TICKET_SUCCESS",
    
    GET_ALL_TICKETS: "GET_ALL_TICKETS",
    GET_ALL_TICKETS_SUCCESS: "GET_ALL_TICKETS_SUCCESS",
    GET_OPEN_TICKETS: "GET_OPEN_TICKETS",
    GET_OPEN_TICKETS_SUCCESS: "GET_OPEN_TICKETS_SUCCESS",
    GET_MY_TICKETS: "GET_MY_TICKETS",
    GET_MY_TICKETS_SUCCESS: "GET_MY_TICKETS_SUCCESS",
    VIEW_TICKET: "VIEW_TICKET",
    VIEW_TICKET_SUCCESS: "VIEW_TICKET_SUCCESS",

    ASSIGN_TO_ME: "ASSIGN_TO_ME",
    ASSIGN_TO_ME_SUCCESS: "ASSIGN_TO_ME_SUCCESS",
    ASSIGN_TO_SOMEONE: "ASSIGN_TO_SOMEONE",
    ASSIGN_TO_SOMEONE_SUCCESS: "ASSIGN_TO_SOMEONE_SUCCESS",
    REASSIGN_TICKET: "REASSIGN_TICKET",
    REASSIGN_TICKET_SUCCESS: "REASSIGN_TICKET",
    
    SET_TICKET_STATUS: "SET_TICKET_STATUS",
    SET_TICKET_STATUS_SUCCESS: "SET_TICKET_STATUS_SUCCESS",

    SEARCH: "SEARCH",
    SEARCH_SUCCESS: "SEARCH_SUCCESS",
    
    ACTION_FAIL: "ACTION_FAIL"
}