export default actionType = {
    CREATE_TICKET: "CREATE_TICKET",
    CREATE_TICKET_SUCCESS: "CREATE_TICKET_SUCCESS",
    
    GET_ALL_TICKETS: "GET_ALL_TICKETS",
    GET_ALL_TICKETS_SUCCESS: "GET_ALL_TICKETS_SUCCESS",
    GET_OPEN_TICKETS: "GET_OPEN_TICKETS",
    GET_MY_TICKETS: "GET_MY_TICKETS",
    VIEW_TICKET: "VIEW_TICKET",

    ASSIGN_TICKET: "ASSIGN_TICKET",
    ASSIGN_TICKET_SUCCESS: "ASSIGN_TICKET_SUCCESS",
    
    SET_TICKET_STATUS: "SET_TICKET_STATUS",
    SET_TICKET_STATUS_SUCCESS: "SET_TICKET_STATUS_SUCCESS",

    SEARCH: "SEARCH",
    SEARCH_SUCCESS: "SEARCH_SUCCESS",

    VIEW_AGENTS: "VIEW_AGENTS",
    VIEW_AGENTS_SUCCESS: "VIEW_AGENTS_SUCCESS",
    
    ACTION_FAIL: "ACTION_FAIL"
}